name: ci

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'docs-content/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'docs-content/**'
      - '*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          npm install --ignore-scripts
      - name: Run tests
        run: |
          npm test --color=always -- -c -t0
