#!/bin/sh
set -e
MODULE=$(echo "$0" | sed s,.*runtestsuite-,,g)
PACKAGE=$(echo "$0" | sed s,.*runtestsuite-module-,,g)
SEDCMD="-e s,require[\(][[\'][.][.]/[.][.]/[.][.][\'][\)],require\(\'tap\'\),g -e  s,require[\(][[\'][.][.]/[.][.][\'][\)],require\(\'$PACKAGE\'\),g"
export MODULE

tmpdir=$(mktemp -d)
export tmpdir
trap 'rm -rf "$tmpdir"' EXIT INT TERM HUP

cd $MODULE
find test -name '*.js' -print0 | \
    xargs -n1 -0 \
	  sh -c 'set -e; mkdir -p "$tmpdir/"`echo $3 | sed "s,/[^/]*$,,g"` ; echo "TESTING: $3"; sed $1  "$3" > $2/$3' sedtape "$SEDCMD" "$tmpdir"

cd $tmpdir
tap test
