#!/bin/sh
set -e

PACKAGE=tap
SEDCMD="s,[.][.]\(/[.][.]\)*,tap/,g"

WORKINGTEST="test/base.js test/clean-stacks.js test/clean-yaml-object.js test/diags.js \
             test/extra-from-error.js test/mocha.js test/obj-to-yaml.js test/parse-test-args.js \
             test/point.js test/run.js test/snapshot.js test/spawn.js test/stdin.js test/synonyms.js test/tap.js"
             # FAIL test/test.js
             # FAIL test/stack.js

tmpdir=$(mktemp -d)
export tmpdir
trap 'rm -rf "$tmpdir"' EXIT INT TERM HUP

cp -r test "$tmpdir"
cp -r tap-snapshots "$tmpdir"
cd "$tmpdir"
ln -s /usr/share/nodejs/tap/bin bin
ln -s /usr/share/nodejs/tap/lib lib
ln -s /usr/share/nodejs/tap/package.json package.json
# emulate travis for avoiding timeout
CI=1 TRAVIS=1 tap -R spec -t 30000 $WORKINGTEST
