#!/bin/sh
set -e
MODULE=$(echo "$0" | sed s,.*runtestsuite-,,g)
PACKAGE=$(echo "$0" | sed s,.*runtestsuite-module-,,g)
SEDCMD="-e s,require[\(][[\'][.][.]/[\'][\)],require\(\'tap\'\),g -e  s,require[\(][\'][.]/[\'][\)],require\(\'$PACKAGE\'\),g"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT INT TERM HUP

cd $MODULE
echo 'test.js' | \
    xargs -n1  \
	  sh -c 'set -e; echo "TESTING: $3"; sed $1 < $3 > $2/$3' sedtape "$SEDCMD" "$tmpdir"

cd $tmpdir
tap *.js
